version: "3"
services:
  obcpp:
    image: ghcr.io/tritonuas/obcpp:jetson
    runtime: nvidia
    network_mode: "host"
    #ports:
    #  - 5010:5010
  not-stolen-israeli-code: 
    image: ghcr.io/tritonuas/not-stolen-israeli-code:latest
    ports:
      - 5069:5000
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
volumes:
  sitl:
