# TODO: setup env variables https://docs.docker.com/compose/environment-variables/
version: "3"
services:
  sitl:
    image: tritonuas/plane.rascal
    network_mode: "host"
    environment:
      - "SITL_HOME=38.31542593549111,-76.55062632801757,8,0"
      - SITL_SPEEDUP=1
    volumes:
      - sitl:/app/logs
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
volumes:
  sitl: