#ifndef INCLUDE_UTILITIES_CONSTANTS_HPP_
#define INCLUDE_UTILITIES_CONSTANTS_HPP_

// Competition specs
const int NUM_AIRDROP_BOTTLES = 5;

// Server
const int SERVER_PORT = 8080;

#endif  // INCLUDE_UTILITIES_CONSTANTS_HPP_
