name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: clang-tidy 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tritonuas/obcpp:main
    steps:
      - name: Create directory
        run: mkdir -p /home/tuas/obcpp

      - name: Clone Repo
        run: git clone git@github.com:tritonuas/obcpp.git /home/tuas/obcpp
        env:
          REPO_KEY: ${{secrets.ACTION_PAT}}

      - name: Set up Cmake
        run: cd /home/tuas/obcpp && mkdir build && cd build && cmake ..

      - name: Run clang-tidy
        run: cd build && make lint 



