name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: clang-tidy 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tritonuas/obcpp:main
    steps:
      - name: Create directory
        run: mkdir -p /home/tuas/obcpp

      - name: Clone Repo
        run: git clone https://oauth2:${{secrets.GITHUB_TOKEN}}@github.com/tritonuas/obcpp.git /home/tuas/obcpp

      - name: Set up Cmake
        run: cd /home/tuas/obcpp && mkdir build && cd build && sudo cmake -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" ..

      - name: Run clang-tidy
        run: cd /home/tuas/obcpp/build && sudo make test
