name: Lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  # home directory of user in obcpp docker image
  HOME_DIR: /home/tuas
  # https://stackoverflow.com/a/71158878
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  test:
    name: cpplint 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tritonuas/obcpp:main
    steps:
      - name: Create directory
        run: mkdir -p "$HOME_DIR/obcpp"

      - name: Clone Repo
        run: git clone --branch $BRANCH_NAME https://oauth2:${{secrets.GITHUB_TOKEN}}@github.com/tritonuas/obcpp.git $HOME_DIR/obcpp

      - name: Set up Cmake
        # uses ${CMAKE_PREFIX_PATH} set in Dockerfile env
        run: cd "$HOME_DIR/obcpp" && rm -rf build && mkdir build && cd build && sudo cmake -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" ..

      - name: Run cpplint
        run: cd "$HOME_DIR/obcpp/build" && sudo make lint
