name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: clang-tidy 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tritonuas/obcpp:main
    steps:
      - name: Clone Repo
        run: git clone git@github.com:tritonuas/obcpp.git 

      - name: Create build dir
        run: mkdir build

      - name: Set up Cmake
        run: cd build && cmake ..

      - name: Run clang-tidy
        run: cd build && make lint 



